---
- import_role:
    name: aws_workshop_login_page
  when: create_login_page

- name: User Projects
  include_role:
    name: user_projects
  with_sequence: start=1 end={{ usersno }} format=%d
  when: user_projects

- name: Make sure we go back to openshift project
  shell: "oc project openshift"

- name: Import Images
  shell: "oc import-image mongodb:3.2 | oc import-image nodejs | oc import-image postgresql | oc import-image php | oc import-image fuse7-java-openshift:1.0 | oc import-image fuse7-java-openshift:1.1"
  ignore_errors: true

- import_role:
    name: provision_che
  when: che

- import_role:
    name: provision_fuse
  when: fuse

- import_role:
    name: provision_sso
  when: sso

- import_role:
    name: provision_threescale
  when: threescale

- import_role:
    name: provision_backend
  when: backend

- import_role:
    name: provision_apicurio
  when: apicurio

- import_role:
    name: provision_gogs
  when: gogs

- import_role:
    name: provision_microcks
  when: microcks