---
- name: Make sure we go back to default project
  shell: "oc project default"

#- name: Create Gogs app
#  shell: "oc new-app -f https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-template.yaml \
#  -p GOGS_VERSION=0.11.34 -p SKIP_TLS_VERIFY=true -p HOSTNAME=gogs.{{ ocp_apps_domain }} -n {{ gogs_project }}"
#  when: configure_only == 'false'
#  register: create_gogs_app
#  failed_when: create_gogs_app.stderr != '' and 'already exists' not in create_gogs_app.stderr

- name: Create Gogs app
  shell: "oc new-app -f https://raw.githubusercontent.com/epe105/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml \
  -p GOGS_VERSION=0.11.34 -p SKIP_TLS_VERIFY=true -p HOSTNAME=gogs.{{ ocp_apps_domain }} -n {{ gogs_project }}"
  when: configure_only == 'false'
  register: create_gogs_app
  failed_when: create_gogs_app.stderr != '' and 'already exists' not in create_gogs_app.stderr

- name: Wait until Gogs API is available
  uri:
    url: http://gogs.{{ocp_apps_domain}}
    method: GET
    follow_redirects: safe
    validate_certs: no
  register: wait_gogs_result
  until: wait_gogs_result is succeeded
  ignore_errors: yes
  retries: 15
  delay: 30
  when: create_realms

- name: Create Gogs users
  uri:
    url: http://gogs.{{ ocp_apps_domain }}/user/sign_up
    method: POST
    follow_redirects: safe
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "user_name={{ item }}&password=openshift&retype=openshift&email={{ item }}@example.com"
    validate_certs: no
    status_code: 200
  register: create_tenant_result
  ignore_errors: true
  with_sequence: start=0 end={{ usersno }} format=user%d
  when: create_realms

- debug: var=create_tenant_result

- name: Get Git Repo
  uri:
    url: 'https://raw.githubusercontent.com/RedHatWorkshops/dayinthelife-integration/master/support/templates/gogs.json'
    return_content: yes
  register: get_gitrepo

- debug: var=get_gitrepo.content

- name: Config repo
  uri:
    url: 'http://gogs.{{ ocp_apps_domain }}/api/v1/repos/migrate'
    method: POST
    body: "{{ get_gitrepo.content | regex_replace('USER_ID', item) }}"
    body_format: json
    user: "user{{ (item|int) - 1 }}"
    password: "openshift"
    headers:
      Content-Type: "application/json"
    force_basic_auth: yes
    return_content: yes
    validate_certs: no
    status_code: 201
  with_sequence: start=2 end={{ (usersno | int) + 1 }}
  register: config_repo
  failed_when: config_repo.status != 201 and 'already exists' not in config_repo.content

- name: Get WWW Git Repo
  uri:
    url: 'https://raw.githubusercontent.com/RedHatWorkshops/dayinthelife-integration/master/support/templates/gogs-www.json'
    return_content: yes
  register: get_gitrepo

- debug: var=get_gitrepo.content

- name: Config repo
  uri:
    url: 'http://gogs.{{ ocp_apps_domain }}/api/v1/repos/migrate'
    method: POST
    body: "{{ get_gitrepo.content | regex_replace('USER_ID', item) }}"
    body_format: json
    user: "user{{ (item|int) - 1 }}"
    password: "openshift"
    headers:
      Content-Type: "application/json"
    force_basic_auth: yes
    return_content: yes
    validate_certs: no
    status_code: 201
  with_sequence: start=2 end={{ (usersno | int) + 1 }}
  register: config_repo
  failed_when: config_repo.status != 201 and 'already exists' not in config_repo.content
